### ISSUE TITLE
Wrong join in run-filter?

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ixmp4#67]
In 

https://github.com/iiasa/ixmp4/blob/3f45bba201de4a448f5e7be930b9e6593fb59d49/ixmp4/data/db/filters/run.py#L29

the Run-table is joined to TimeSeries. But I don't understand why Run should *always* be joined to TimeSeries, which seems wrong when filtering just for the runs or for meta-indicators...

Is this an error?

**Comment by glatterf42** [comment]
If you remove these lines and run the `core/test_run.py` tests, they will pass, but yield this output:
```python
=========================================== warnings summary ============================================
tests/core/test_run.py::TestCoreRun::test_filter_run[test_sqlite_mp]
tests/core/test_run.py::TestCoreRun::test_filter_run[test_api_sqlite_mp]
  /home/fridolin/ixmp4/.venv/lib/python3.12/site-packages/pandas/io/sql.py:1600: SAWarning: SELECT statement has a cartesian product between FROM element(s) "run" and FROM element "region".  Apply join condition(s) between each element to resolve.
    return self.con.execute(sql, *args)

tests/core/test_run.py::TestCoreRun::test_filter_run[test_api_sqlite_mp]
  /home/fridolin/ixmp4/ixmp4/data/db/base.py:275: SAWarning: SELECT statement has a cartesian product between FROM element(s) "iamc_timeseries" and FROM element "run".  Apply join condition(s) between each element to resolve.
    return self.session.execute(_exc).scalar_one()

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
My guess is that `RunFilter` is widely used (almost every other kind of filter is inheriting from it, so that's why we could have an SQL execute statement here that isn't joined with the `Run` table. And SQLAlchemy tells us that in this case, it doesn't quite know how to join the tables and we should clarify it by applying join conditions (if I understand the warnings correctly).

**Comment by meksor** [comment]
Not an error. That just the default join method because thats how it almost always needs to work. 
Just override the function with `return exc` to avoid the join. 
Or find a better structure for this in general...
